TooBuzyWebClient/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TooBuzyWebClient.Models
{
    public class Customer
    {
        public Customer()
        {
            Tables = new List<Table>();
            Createdate = DateTime.Now;
        }
        public int Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public int ZipCode { get; set; }
        public string Address { get; set; }
        public int PhoneNo { get; set; }
        public string Password { get; set; }
        public List<Table> Tables { get; set; }
        public DateTime Createdate { get; set; }
    }
}

TooBuzyWebClient/Controllers/BookingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TooBuzyWebClient.Controllers
{
    public class BookingController : Controller
    {
        private TooBuzyServiceReference.TooBuzyServiceClient proxy = new TooBuzyServiceReference.TooBuzyServiceClient("TooBuzyServies");

        // GET: Booking
        public ActionResult Index()
        {
            return View();
        }

        // GET: Booking/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Booking/Create
        public ActionResult Create()
        {
            ViewBag.Tables = new SelectList(proxy.GetAllTables().ToList(), "Id", "TableNo");
            return View();
        }

        // POST: Booking/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Booking/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Booking/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Booking/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Booking/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

TooBuzyWebClient/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TooBuzyWebClient.TooBuzyServiceReference;

namespace TooBuzyWebClient.Controllers
{
    public class CustomerController : Controller
    {
        private TooBuzyServiceReference.TooBuzyServiceClient proxy = new TooBuzyServiceReference.TooBuzyServiceClient("TooBuzyServies");

        public ActionResult Index()
        {
            return View(proxy.GetAllCustomers().ToList());
        }
        public ActionResult Details(int Id)
        {
            Customer cus = proxy.GetCustomerById(Id);
            if (cus == null)
            {
                return HttpNotFound();
            }
            return View(cus);
        }
        public ActionResult _MenuPartial(int Id)
        {
            Menu menu = proxy.GetMenuById(Id);
            if (menu == null)
            {
                return HttpNotFound();
            }
            return PartialView(menu);
        }
    }
}

TooBuzyWebClient/Views/Customer/Details.cshtml
@model TooBuzyWebClient.TooBuzyServiceReference.Customer
@{
    ViewBag.Title = Model.Name + " detaljer";
}

    <div class="jumbotron">
        <h1>@Model.Name</h1>
        <p class="lead">Vores type mad: @Model.Type</p>
        <i>Adresse: @Model.Address - @Model.ZipCode</i>
        <i>Antal borde: @Model.Tables.Count()</i>
        <a href="@Url.Action("Create", "Booking")" class="btn btn-success pull-right">Create booking</a>

    </div>
<div class="row">
    @Html.Action("_MenuPartial", "Customer", new { Id = Model.MenuId })
</div>

TooBuzyWebClient/Views/Customer/Index.cshtml
@model List<TooBuzyWebClient.TooBuzyServiceReference.Customer>

@{
    ViewBag.Title = "TooBuzy - Vores restauranter";
}

<h2 class="text-center">Udvalget af restauranter</h2>
<div class="row">
    @foreach (var item in Model.OrderBy(x => x.Name))
    {
    <div class="col-lg-4 col-md-4 col-sm-6 productBox">
        <div>
            <img class="img-thumbnail productImg" src="~/Content/pictures/standard picture.png" />
        </div>
        <div>
            <h3 class="text-center">@item.Name</h3>
            <i>@item.Type</i>
            <p class="pull-right"><a class="btn btn-info" href="@Url.Action("Details", "Customer", new { Id = item.Id })">More ></a></p>
        </div>
    </div>
    }

</div>

TooBuzyWebClient/Views/Customer/_MenuPartial.cshtml
@model TooBuzyWebClient.TooBuzyServiceReference.Menu
@{ 
    Layout = "";
}

    <table class="table">
        <thead>
            <tr>
                <th>
                    <p>Produkt Navn:</p>
                </th>
                <th>
                    <p>Beskrivelse:</p>
                </th>
                <th>
                    <p>Pris:</p>
                </th>
                <th>
                    Tilføj  
                </th>
            </tr>
        </thead>
        @foreach (var item in Model.Products)
        {
            if (item.IsDeleted != true)
            {
                <tr>
                    <th>
                        <p>@item.Name</p>
                    </th>
                    <th>
                        <p>@item.Description </p>
                    </th>
                    <th>
                        <p>@item.Price</p>
                    </th>
                    <th>
                        @*Skal tilføjes et order event*@
                        <button type="button" class="btn btn-success">Tilføj</button>
                    </th>
                </tr>
            }

        }
        <tbody></tbody>
    </table>